const APP_LOADING_STARTS    = 'APP_LOADING_STARTS';
const APP_LOADING_ENDS      = 'APP_LOADING_ENDS';
const LISTING_FAILED        = 'LISTING_FAILED';
const LISTING_SUCCESS       = 'LISTING_SUCCESS';
const PAGINATE_LIST         = 'PAGINATE_LIST';
const PAGE_LIMIT            = 3;
const PRODUCT_DEFAULT_EXCERPT = "Some quick example text to build on the card title and make up the bulk of the card's content.";
const PRODUCT_LOADING_STARTS = "PRODUCT_LOADING_STARTS";
const PRODUCT_LOADING_ENDS = "PRODUCT_LOADING_ENDS";
const PRODUCT_FETCING_SUCCESS = "PRODUCT_FETCING_SUCCESS";
const PRODUCT_FETCING_FAILED = "PRODUCT_FETCING_FAILED";

export {
    PAGE_LIMIT,
    APP_LOADING_STARTS,
    APP_LOADING_ENDS,
    PRODUCT_DEFAULT_EXCERPT,
    LISTING_SUCCESS,
    LISTING_FAILED,
    PAGINATE_LIST,
    PRODUCT_LOADING_ENDS,
    PRODUCT_LOADING_STARTS,
    PRODUCT_FETCING_SUCCESS,
    PRODUCT_FETCING_FAILED   
}